### ISSUE TITLE
[Feature Request] Support for Installing Optional Operands from the CLI after successful installation of Operator

### ISSUE THREAD

**Issue by Lucifergene** [operator-framework/kubectl-operator#156]
Currently, in the case of "Openshift Serverless operator", I am able to install the operator with the following command:

```
k operator install serverless-operator --create-operator-group -v 1.32.1 -c stable
```

But in order to use the operator, I still have to manually create the "Knative Serving/Knative Eventing" operands/sub-resources to use the operator. Either I have to use the UI or apply the YAML.
![2024-05-14_23-21](https://github.com/operator-framework/kubectl-operator/assets/47265560/deae3b15-99d0-40a1-b3b6-b06628bbf2e5)

I want to do this step from the CLI itself just like the way we install the operator.

**Comment by joelanford** [comment]
This is out-of-scope for the `kubectl operator` plugin. This plugin's focus is purely on operator lifecycling. I think it would be a very large increase in scope to also attempt to handle operands.
