### ISSUE TITLE
Error while uninstalling operator

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/kubectl-operator#24]
Tried installing `cockroachdb` operator using the commands as given in `demo.sh` with the binary built from master.

Steps followed:
1. Install operator - `kubectl-operator install cockroachdb --create-operator-group -v 2.1.1`
Output - Operator is installed successfully.

2. Uninstall operator - `kubectl-operator uninstall cockroachdb --delete-crds --delete-operator-groups`
Output:

```
subscription "cockroachdb" deleted
uninstall operator: delete clusterserviceversion "": resource name may not be empty
```

When I check for the csv available in cluster after running the uninstall command, I get this:
```
➜  kubectl-operator git:(main) k get csv --all-namespaces | grep -i cockroachdb
default           cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
kube-node-lease   cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
kube-public       cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
kube-system       cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
olm               cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
operators         cockroachdb.v2.1.1   CockroachDB      2.1.1     cockroachdb.v2.0.9   Succeeded
```

The crds are not deleted either:
```
➜  kubectl-operator git:(main) k get crds --all-namespaces | grep -i cockroachdb
cockroachdbs.charts.helm.k8s.io               2020-11-03T03:01:41Z
```

Expected output: The operator is uninstalled successfully and all the resources are deleted.

**Comment by joelanford** [comment]
Thanks @varshaprasad96! What version of OLM are you using? I'm not able to reproduce this with OLM v0.16.1

**Comment by joelanford** [comment]
And _now_ I just ran into this. So it seems to be intermittent or triggered by something a little more specific.
