### ISSUE TITLE
Add debug command to root command for installation debugging

### ISSUE THREAD

**Issue by exdx** [operator-framework/kubectl-operator#36]
OLM users right now have a hard time debugging operator installations that have gone awry. They are required to dig deep into internal APIs, such as InstallPlans, to piece together what happened. These APIs are not well documented and the catalog operator logs may be misleading. It would be helpful if we had a command to help piece together what happened when something goes wrong for end users. 

I thought about writing a `olmdebug` CLI tool but it may make more sense for this functionality to live in this project. WDYT about adding a debug command to the tool? Here are some thoughts on the usage:

`kubectl operator debug <package>`

- Often times users install operators via the UI or create a subscription pointing to a package, they may not know the CSV name specifically. By accepting a package name, the command could determine the CSV involved in the installation and return an amalgamation of CSV status, InstallPlan Status, the catalog involved, etc
- Over time, this command could get more sophisticated and return suggested fixes to the user, similar to how the `cargo` rust compiler detects compilation errors and returns ways to resolve them.

**Comment by joelanford** [comment]
Sounds like a great idea to me!
