### ISSUE TITLE
Doc: Install steps? 

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/kubectl-operator#4]
It'd be great to have some pointers for installing this in the Readme. Perhaps there is other documentation that could simply be linked?

**Comment by joelanford** [comment]
It will hopefully be installable via `krew` in the near future. See https://github.com/kubernetes-sigs/krew-index/pull/737

I've been waiting on that to merge to write the install steps. For now, clone the repo, and run `make install`. That will copy it into `$GOPATH/bin`, so if that's on your path, `kubectl` will find it and you can run `kubectl operator`
